package main

//
// a word-count application "plugin" for MapReduce.
//
// go build -buildmode=plugin wc.go
//

import "6.5840/mr"
import "unicode"
import "strings"
import "strconv"

// The map function is called once for each file of input. The first
// argument is the name of the input file, and the second is the
// file's complete contents. You should ignore the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.
//传入文件名和文件内容，返回键值对数组
func Map(filename string, contents string) []mr.KeyValue {
	// function to detect word separators.
	//检测单词的分割符
	ff := func(r rune) bool { return !unicode.IsLetter(r) }

	// split contents into an array of words.
	//将content根据分割副分割为不同的单词并存入数组之中
	words := strings.FieldsFunc(contents, ff)

	//kva是键值对数组
	//kv是键值对
	kva := []mr.KeyValue{}
	for _, w := range words {
		kv := mr.KeyValue{w, "1"}
		kva = append(kva, kv)
	}
	return kva
}

// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
func Reduce(key string, values []string) string {
	// return the number of occurrences of this word.
	//返回单词出现的次数，即value数组的长度
	//返回string类型的数字
	return strconv.Itoa(len(values))
}
